In [ ]:
print ("machine learning started on 10/07/2023 at 06:05PM")

machine learning started on 10/07/2023 at 06:05PM


#Numpy


In [ ]:
#single dimentional numpy array
import numpy as np
n1 = np.array([1,2,3,4])
print(n1)
type(n1)

[1 2 3 4]


numpy.ndarray

In [ ]:
#multi dimensional numpy array
import numpy as np
n2=np.array([[1,2,3,4],[5,6,7,8]])
n2
print(n2,type(n2))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [ ]:
#implementing numpy with zeros
import numpy as np
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [ ]:
#implementing numpy with zeros
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#implementing numpy with same number
n5=np.full((2,3),19)
n5

array([[19, 19, 19],
       [19, 19, 19]])

In [ ]:
#initializing numpy array with a range
n6=np.arange(10,50)#10 is inclusive, 50 is exclusive, if you want to inclue 50 use range 51
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#initializing numoy arrray with range and step
n7=np.arange(10,200,10)
n7

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [ ]:
#initializing NumPY array with random numbers
n8=np.random.randint(10,20,2)#10-min 20-max 2-number of numbers to be selected
n8

array([11, 12])

In [ ]:
#checking the shape of numpy array
n9=np.array([[1,2,3],[4,5,6]])
n9.shape

(2, 3)

In [ ]:
n9.shape=(3,2)
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#joining numpy arrays using vstack,hstack,column_stack
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.vstack((a1,a2))
a4=np.hstack((a1,a2))
a5=np.column_stack((a1,a2))
print("a3:",a3,"\n a4:",a4,"\n a5:",a5)

a3: [[1 2 3]
 [4 5 6]] 
 a4: [1 2 3 4 5 6] 
 a5: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
b1=np.array([1,2,3,4,56,2,3,4,5])
b2=np.array([1,2,3,4,5,6,7,8,9])
b3=np.intersect1d(b1,b2)
b4=np.setdiff1d(b1,b2)
print(b3,b4)

[1 2 3 4 5] [56]


In [ ]:
b5=np.sum([b1,b2])
print(b5)
b6=np.sum([b1,b2],axis=0)
print(b6)
b7=np.sum([b1,b2],axis=1)
print(b7)

125
[ 2  4  6  8 61  8 10 12 14]
[80 45]


In [ ]:
#basic addition,sub.multiply,div
b8=b1+1
print(b8)
b9=b1-1
print(b9)
b10=b1*2
print(b10)
b11=b1/2
print(b11)

[ 2  3  4  5 57  3  4  5  6]
[ 0  1  2  3 55  1  2  3  4]
[  2   4   6   8 112   4   6   8  10]
[ 0.5  1.   1.5  2.  28.   1.   1.5  2.   2.5]


In [ ]:
#mean,median,standard deviation
b20=np.array([10,20,30,40,50,60])
print(np.mean(b20))
print(np.std(b1))
print(np.median(b1))

35.0
16.696270005566078
3.0


# Pandas

In [ ]:
# used for  data maniulation
# single-dimensional data structures - Series Object
# Multi-dimensional - Data Frame
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
#changing index
s1=pd.Series([1,2,3],index=['a','b','c'])
s1

a    1
b    2
c    3
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s2=pd.Series({'a':100,'b':200},index=['b','a'])
s2

b    200
a    100
dtype: int64

In [ ]:
s4=pd.Series([1,2,3,4,5,6,7,8,9])
s4[1]

2

In [ ]:
s4[-3:]#last three elements

6    7
7    8
8    9
dtype: int64

In [ ]:
s4+1

0     2
1     3
2     4
3     5
4     6
5     7
6     8
7     9
8    10
dtype: int64

In [ ]:
s4+s4

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [ ]:
#data frame
sp=pd.DataFrame({'name':['bob','prasu','naidu'],'marks':[100,200,50]})
sp

name  marks
0    bob    100
1  prasu    200
2  naidu     50

In [ ]:
iris=pd.read_csv('iris.csv')
iris.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [ ]:
iris.tail(10)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
iris.shape

(150, 5)

In [ ]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.iloc[0:3,0:2]#here max limit is exclusive

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [ ]:
iris.loc[1:4,('Sepal.Length','Petal.Length')]#here it is inclusive

Sepal.Length  Petal.Length
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

In [ ]:
iris.drop('Species',axis=1)#drop column

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
iris.drop([1,2,3],axis=0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [ ]:
iris.mean()

<ipython-input-64-7eed97565d6e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.mean()


Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [ ]:
iris.median()

<ipython-input-65-7f9b4600b8ea>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.median()


Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [ ]:
iris.min()

Sepal.Length       4.3
Sepal.Width        2.0
Petal.Length       1.0
Petal.Width        0.1
Species         setosa
dtype: object

In [ ]:
iris.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [ ]:
def half(s):
   return s*0.5
iris[['Sepal.Width']].apply(half)

Sepal.Width
0           1.75
1           1.50
2           1.60
3           1.55
4           1.80
..           ...
145         1.50
146         1.25
147         1.50
148         1.70
149         1.50

[150 rows x 1 columns]

In [ ]:
iris['Species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: Species, dtype: int64

In [ ]:
iris.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

#Numpy vs Lists - Time Taken

In [ ]:
from time import process_time

In [ ]:
list1 = [i for i in range(1000)]
start_time = process_time()
list1 = [i+5 for i in list1]
end_time = process_time()
print(end_time-start_time)

0.0002751469999999756


In [ ]:
import numpy as np

In [ ]:

arr1 = np.array([i for i in range(1000)])
start_time = process_time()
arr1 += 5
end_time = process_time()
print(end_time-start_time)


0.0009981980000000057


#Numpy in depth

In [ ]:
#single dimensional array
numpy1 = np.array([1,2,3])
print(numpy1)

[1 2 3]


In [ ]:
numpy2 = np.array([(1,2,3,4),(1,2,4,3)])
print(numpy2)
print(len(numpy2))
print(numpy2.shape)

[[1 2 3 4]
 [1 2 4 3]]
2
(2, 4)


In [ ]:
#converting numpy integer value into float
numpy3 = numpy2.astype(float)
print(numpy3)

[[1. 2. 3. 4.]
 [1. 2. 4. 3.]]


#Initial  Placeholders in numpy array


In [ ]:
#create a numpy array of all zeroes of single dimentional
x = np.zeros((2,))
print(x)

[0. 0.]


In [ ]:
#create a numpy array of all zeroes multi dimensional
x = np.zeros((2,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# creation of a numpy aarray of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creation of numpy array of same value of required dimension
z = np.full((2,3),33)
z

array([[33, 33, 33],
       [33, 33, 33]])

In [ ]:
# create an identity matrix
#all the diagonal values should be 1 and other  values should  be  zero
a= np.eye(5)
print('default we get an matrix of float values',a)
b=a.astype(int)
print('converted into int type using astype \n',b)

default we get an matrix of float values [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
converted into int type using astype 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# create a numpy array with random values
a= np.random.randint(3,5,(4,5))#range and ssize included in randint
a

array([[3, 3, 3, 4, 3],
       [3, 3, 3, 4, 3],
       [4, 4, 3, 3, 4],
       [4, 4, 4, 3, 3]])

In [ ]:
b=np.random.random((3,5)) #only size will be included. the range will be inbetween 0 and 1
b

array([[0.68214986, 0.13210716, 0.39783856, 0.29802136, 0.5646829 ],
       [0.29162395, 0.65440655, 0.01648474, 0.07709663, 0.53469467],
       [0.05267631, 0.20562867, 0.43196135, 0.15156518, 0.47614522]])

In [ ]:
# array of evenly spaced values
d = np.linspace(10,30,10)
print(d)
d_int=d.astype(int)
print(d_int)

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]
[10 12 14 16 18 21 23 25 27 30]


In [ ]:
# array of evenly spaced values --> specifying step
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [ ]:
#convert a list into a numpy array
list2c= [10,20,20,20,50]
np_array = np.asarray(list2c)
print(np_array)
print(type(np_array))

[10 20 20 20 50]
<class 'numpy.ndarray'>


#Analysing a Numpy Array

In [ ]:
c = np.random.randint(10,100,(5,5))

In [ ]:
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the datatype of the values in the array
print(c.dtype)

int64


#Mathematical Operations on a np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,0]
print(list1 + list2)#concatenates or joins the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a,'\n b= \n',b)

[[2 9 1]
 [7 9 2]
 [1 6 2]] 
 b= 
 [[16 10 14]
 [14 15 11]
 [10 10 19]]


In [ ]:
print(a+b)#in list if we add two lists it will concatenate the lists but in numpy it adds element wise

[[18 19 15]
 [21 24 13]
 [11 16 21]]


In [ ]:
print(np.add(a,b))

[[18 19 15]
 [21 24 13]
 [11 16 21]]


In [ ]:
print(np.subtract(a,b))

[[-14  -1 -13]
 [ -7  -6  -9]
 [ -9  -4 -17]]


In [ ]:
print(np.multiply(a,b))

[[ 32  90  14]
 [ 98 135  22]
 [ 10  60  38]]


#Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 0 8]
 [7 4 7]]
(2, 3)


In [ ]:
trans = np.transpose(array)#(2,3) matrix will be transposed into (3,2)
print(trans)
print(trans.shape)

[[9 7]
 [0 4]
 [8 7]]
(3, 2)


In [ ]:
trans2 = trans.T
trans2
print(trans2 == array)

[[ True  True  True]
 [ True  True  True]]


In [ ]:
#reshapinfg an array
a= np.random.randint(0,10,(2,3))
print(a)

[[3 9 6]
 [2 1 3]]


In [ ]:
b = a.reshape(3,2)
print(b)

[[3 9]
 [6 2]
 [1 3]]


#Numpy problem Solving

In [ ]:
#1. Given a list [5,10,0,200]. now the output should be [10,15,5,205]
lst = [5,10,0,200]
lst = [i+5 for i in lst]
print(lst)

[10, 15, 5, 205]


In [ ]:
#solving this using numpy
import numpy as np
lst = np.array([5,10,0,200])
lst = lst+5
print(lst)

[ 10  15   5 205]
